github: [codemonkeysio, jchiarulli]
patreon: codemonkeys?fan_landing=true
custom:
  [
    'https://paypal.me/codemonkeystech?locale.x=en_US',
    'https://www.subscribestar.com/code-monkeys',
    'https://venmo.com/u/codemonkeys'
  ]
