github: jchiarulli
patreon: codemonkeys?fan_landing=true
custom:
  [
    'https://paypal.me/codemonkeystech?locale.x=en_US',
    'https://www.subscribestar.com/code-monkeys',
    'https://venmo.com/code?user_id=3337094999048192411&created=1628623642.5328379&printed=1'
  ]
